# Generated by Django 4.1.2 on 2022-11-13 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.AddField(
            model_name='images',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_examining', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='patient_xray', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='x_ray',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
